import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>SÓLÓLÓL</title>
        <meta name="author" content="Þorkell Máni Þorkelsson" />
        <meta name="author" content="Rebekka Ashley Egilsdóttir" />
        <meta
          name="description"
          content="Stjórnborð Sólólól. Stýrir hvaða sól Sólólólin lýsir upp umhverfi sitt sem"
        />

        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </head>
    </html>
  );
}
